use super::*;

fn config_markdown(sections: Vec<&str>) -> OutputConfig {
    OutputConfig {
        format: Some("markdown".to_string()),
        required_sections: sections.into_iter().map(|s| s.to_string()).collect(),
        ..Default::default()
    }
}

fn config_json() -> OutputConfig {
    OutputConfig {
        format: Some("json".to_string()),
        ..Default::default()
    }
}

#[test]
fn test_no_format_passes() {
    let config = OutputConfig::default();
    let result = validate_skill_output("anything", &config);
    assert!(result.is_ok());
}

#[test]
fn test_markdown_all_sections_present() {
    let output = "## Summary\nAll good.\n\n## Details\nMore info.";
    let config = config_markdown(vec!["Summary", "Details"]);
    let result = validate_skill_output(output, &config);
    assert!(result.is_ok());
}

#[test]
fn test_markdown_missing_sections() {
    let output = "## Summary\nAll good.";
    let config = config_markdown(vec!["Summary", "Details", "Recommendations"]);
    let result = validate_skill_output(output, &config);
    assert!(result.is_err());
    if let Err(OutputValidationError::MissingSections(missing)) = result {
        assert_eq!(missing, vec!["Details", "Recommendations"]);
    } else {
        panic!("Expected MissingSections error");
    }
}

#[test]
fn test_json_valid() {
    let output = r#"{"key": "value", "num": 42}"#;
    let config = config_json();
    let result = validate_skill_output(output, &config);
    assert!(result.is_ok());
}

#[test]
fn test_json_invalid() {
    let output = "This is not JSON at all";
    let config = config_json();
    let result = validate_skill_output(output, &config);
    assert!(result.is_err());
    assert!(matches!(result, Err(OutputValidationError::InvalidJson(_))));
}

#[test]
fn test_json_extracted_from_code_block() {
    let output = "Here is the result:\n```json\n{\"status\": \"ok\"}\n```\nDone.";
    let config = config_json();
    let result = validate_skill_output(output, &config).unwrap();
    assert_eq!(result, r#"{"status": "ok"}"#);
}

#[test]
fn test_json_extracted_from_braces() {
    let output = "Some text before {\"a\": 1} and after";
    let config = config_json();
    let result = validate_skill_output(output, &config).unwrap();
    assert_eq!(result, r#"{"a": 1}"#);
}

#[test]
fn test_repair_prompt_missing_sections() {
    let err =
        OutputValidationError::MissingSections(vec!["Summary".to_string(), "Details".to_string()]);
    let prompt = err.repair_prompt();
    assert!(prompt.contains("Summary, Details"));
    assert!(prompt.contains("## SectionName"));
}

#[test]
fn test_repair_prompt_invalid_json() {
    let err = OutputValidationError::InvalidJson("unexpected token".to_string());
    let prompt = err.repair_prompt();
    assert!(prompt.contains("unexpected token"));
    assert!(prompt.contains("valid JSON"));
}

#[test]
fn test_max_tokens_warning_does_not_reject() {
    let output = "x".repeat(1000);
    let config = OutputConfig {
        format: Some("text".to_string()),
        max_tokens: Some(10), // 10 tokens ~= 40 chars, output is 1000
        ..Default::default()
    };
    // Should pass (warning only, not rejection)
    let result = validate_skill_output(&output, &config);
    assert!(result.is_ok());
}

#[test]
fn test_unknown_format_passes() {
    let config = OutputConfig {
        format: Some("patchset".to_string()),
        ..Default::default()
    };
    let result = validate_skill_output("anything", &config);
    assert!(result.is_ok());
}

#[test]
fn test_markdown_no_required_sections_passes() {
    let config = OutputConfig {
        format: Some("markdown".to_string()),
        required_sections: Vec::new(),
        ..Default::default()
    };
    let result = validate_skill_output("# Hello\nAnything goes", &config);
    assert!(result.is_ok());
}

// --- deterministic_repair tests ---

#[test]
fn test_deterministic_repair_missing_sections() {
    let err = OutputValidationError::MissingSections(vec![
        "Summary".to_string(),
        "Recommendations".to_string(),
    ]);
    let result = deterministic_repair("## Intro\nSome content.", &err);
    assert!(result.is_some());
    let (repaired, succeeded) = result.unwrap();
    assert!(succeeded);
    assert!(repaired.starts_with("## Intro\nSome content."));
    assert!(repaired.contains("## Summary"));
    assert!(repaired.contains("## Recommendations"));
    assert!(repaired.contains("(Section not generated by skill.)"));
}

#[test]
fn test_deterministic_repair_invalid_json_returns_none() {
    let err = OutputValidationError::InvalidJson("unexpected token".to_string());
    let result = deterministic_repair("not json", &err);
    assert!(result.is_none());
}

#[test]
fn test_deterministic_repair_repaired_output_passes_validation() {
    let output = "## Intro\nSome content.";
    let config = config_markdown(vec!["Intro", "Summary"]);
    let err = validate_skill_output(output, &config).unwrap_err();
    let (repaired, _) = deterministic_repair(output, &err).unwrap();
    // The repaired output should now pass validation
    let result = validate_skill_output(&repaired, &config);
    assert!(result.is_ok(), "Repaired output should pass validation: {:?}", result);
}
