use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Wake events generated by the Wake module
/// Uses `kind` tag to avoid conflict with ServerEvent's `type` tag
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum WakeEvent {
    Timer { job_id: String, tag: String },
    FileChanged { path: String, change_type: String },
}

/// Server events pushed to clients via WebSocket
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ServerEvent {
    Heartbeat {
        ts: DateTime<Utc>,
        instance_id: String,
    },
    CommandReceived {
        request_id: String,
        command: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered by the Wake module
    Wake {
        wake: WakeEvent,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when a connector status changes
    ConnectorStatus {
        id: String,
        status: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when a task status changes
    TaskStatus {
        task_id: String,
        title: String,
        status: String,
        progress_current: Option<i32>,
        progress_total: Option<i32>,
        result_summary: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        outcome_kind: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        artifact_count: Option<i32>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        outcome_summary: Option<String>,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when an agent status changes
    AgentStatus {
        agent_id: String,
        name: String,
        status: String,
        current_task_id: Option<String>,
        /// The runtime agent instance identifier (e.g. "code_agent::a1b2c3d4").
        agent_instance_id: String,
        /// The template this instance was spawned from (e.g. "code_agent").
        template_id: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when a key status changes (add/remove/reorder)
    KeyStatusChanged {
        provider: String,
        key_id: String,
        status: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when a chat stream starts
    ChatStreamStarted {
        stream_id: String,
        lane_key: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when a chat stream ends
    ChatStreamEnded {
        stream_id: String,
        lane_key: String,
        status: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when an agent config is created, updated, or deleted
    AgentConfigChanged {
        agent_id: String,
        action: String, // "created" | "updated" | "deleted"
        config_version: u64,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when orchestrator config changes
    OrchestratorConfigChanged {
        model: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when daemon config changes (e.g. execution limits, server settings)
    DaemonConfigChanged {
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when a DAG node starts or completes
    DagNodeStatus {
        task_id: String,
        node_id: String,
        node_title: String,
        agent_id: String,
        /// "started" | "completed" | "failed"
        status: String,
        duration_ms: Option<u64>,
        output_preview: Option<String>,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// A security policy was violated by an agent
    SecurityViolation {
        agent_id: String,
        tool_name: String,
        reason: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// A tool's circuit breaker was tripped due to repeated failures
    CircuitBreakerTripped {
        agent_id: String,
        tool_name: String,
        consecutive_failures: usize,
        reset_after_secs: u64,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// A tool was executed by an agent
    ToolExecuted {
        agent_id: String,
        tool_name: String,
        success: bool,
        duration_ms: u64,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// An LLM call completed
    LlmCallCompleted {
        agent_id: String,
        model: String,
        input_tokens: u32,
        output_tokens: u32,
        cost_usd: f64,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// The skill catalog was updated (skill added, removed, or reloaded)
    SkillCatalogUpdated {
        skill_name: String,
        /// "added" | "removed" | "reloaded"
        action: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// A skill invocation started
    SkillInvocationStarted {
        request_id: String,
        skill_id: String,
        query_preview: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// A skill invocation completed successfully
    SkillCompleted {
        request_id: String,
        skill_id: String,
        duration_ms: u64,
        output_preview: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// A skill invocation failed
    SkillFailed {
        request_id: String,
        skill_id: String,
        error: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// A tool requires interactive human confirmation before execution
    ToolConfirmationRequested {
        request_id: String,
        agent_id: String,
        tool_name: String,
        tool_arguments: serde_json::Value,
        stream_id: Option<String>,
        lane_key: Option<String>,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when SOUL.md personality is updated
    SoulUpdated {
        /// Who initiated: "agent" or "user"
        actor: String,
        /// Update mode: "replace" or "sections"
        mode: String,
        /// SHA-256 hash of the new content
        content_sha256: String,
        /// Path to backup file (if created)
        backup_path: Option<String>,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// A background workflow was started for a lane (Routing V2)
    WorkflowStarted {
        task_id: String,
        lane_key: String,
        title: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// A steering message was accepted into a running workflow's inbox (Routing V2)
    WorkflowSteered {
        task_id: String,
        lane_key: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// A running workflow posted a user-facing progress update (Routing V2)
    WorkflowProgress {
        task_id: String,
        lane_key: String,
        message: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// A follow-up item was queued for a lane (Routing V2)
    FollowupQueued {
        lane_key: String,
        followup_id: i64,
        /// "followup" | "unprocessed_steering"
        kind: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// An extension's observed state changed — T5, E5, `mark_failed`, T5-deny,
    /// T5-gone and §3.7's tool-list refresh (extension design ADR-030).
    ///
    /// The GUI **invalidates** on this and re-reads the row; nothing is ever
    /// rendered from the payload, so a late, dropped or reordered event can
    /// never show a state the daemon is not in (§8, X-18).
    ExtensionStateChanged {
        /// `"mcp"` | `"plugin"`.
        kind: String,
        /// The extension id — a server name, or a plugin directory name.
        id: String,
        /// The record's new state word, or `"removed"` when the declaration is
        /// gone and the row simply disappears.
        state: String,
        /// The load the change belongs to, so the event log stays unambiguous
        /// when a late crash notice arrives after a newer load's events.
        generation: u64,
        /// Set only by a server-driven `tools/list_changed` refresh.
        #[serde(default)]
        tools_changed: bool,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// **S4 moment 1 / 2** — a capability was withheld from a caller
    /// (extension design §7.1, §7.2, §6.2 #13). Deduped per
    /// `(scope, extension, moment)` for ten minutes: the announcement, never
    /// the error.
    ExtensionCapabilityWithheld {
        /// `"mcp"` | `"plugin"`.
        kind: String,
        id: String,
        /// The tool name, capability or skill id the withholding is about.
        subject: String,
        /// `"attempted_use"` | `"surface_assembly"` | `"scheduled_skip"`.
        moment: String,
        /// The record's state word, or `"unrecorded"`.
        state: String,
        /// The dedup scope key — the skill id for `scheduled_skip`.
        scope: String,
        /// The caller held a previous load's handle.
        stale: bool,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// **S4 moment 3** — T1 step 3's dependent scan: one per transition, never
    /// deduped (extension design §3.2 T1, §7.3).
    ExtensionCapabilityWithdrawn {
        /// `"mcp"` | `"plugin"`.
        kind: String,
        id: String,
        /// The record's state word at the transition.
        state: String,
        /// `"disable"` | `"watcher"` | `"declaration_gone"` | `"deny"` |
        /// `"reload"` | `"crash"` | `"server_list_change"` — what the wording is
        /// keyed on, never the state.
        cause: String,
        capabilities: Vec<String>,
        tools: Vec<String>,
        affected_templates: Vec<String>,
        affected_skills: Vec<String>,
        /// The cron-scheduled subset; the owner notice fires only when this is
        /// non-empty.
        affected_cron_skills: Vec<String>,
        /// The daemon's default lane, where the notice was written.
        notice_lane: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// A plugin was loaded and registered its tools
    PluginLoaded {
        plugin_id: String,
        tools: Vec<String>,
    },
    /// A plugin was unloaded (graceful shutdown)
    PluginUnloaded {
        plugin_id: String,
    },
    /// A plugin process crashed unexpectedly
    PluginCrashed {
        plugin_id: String,
        error: String,
        restart_in_secs: u64,
    },
    /// A plugin was disabled by the system or user
    PluginDisabled {
        plugin_id: String,
        reason: String,
    },
    /// A plugin requires capability approval before activation
    PluginPendingApproval {
        plugin_id: String,
        capabilities: Vec<String>,
    },
    /// A plugin needs configuration keys before it can start
    PluginNeedsConfig {
        plugin_id: String,
        missing_keys: Vec<String>,
    },
}

/// The source of an event, identifying which connector or interface originated it.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(tag = "source_type", rename_all = "snake_case")]
pub enum EventSource {
    Telegram { chat_id: String, user_id: String },
    IMessage { chat_id: String, sender: String },
    Discord { channel_id: String, user_id: String, guild_id: Option<String> },
    Gui { connection_id: String },
    Api { request_id: String },
    Internal,
}

#[cfg(test)]
mod tests;
