use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Wake events generated by the Wake module
/// Uses `kind` tag to avoid conflict with ServerEvent's `type` tag
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum WakeEvent {
    Timer { job_id: String, tag: String },
    FileChanged { path: String, change_type: String },
}

/// Server events pushed to clients via WebSocket
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ServerEvent {
    Heartbeat {
        ts: DateTime<Utc>,
        instance_id: String,
    },
    Log {
        level: String,
        message: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    CommandReceived {
        request_id: String,
        command: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered by the Wake module
    Wake {
        wake: WakeEvent,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when a connector status changes
    ConnectorStatus {
        id: String,
        status: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when a task status changes
    TaskStatus {
        task_id: String,
        title: String,
        status: String,
        progress_current: Option<i32>,
        progress_total: Option<i32>,
        result_summary: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        outcome_kind: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        artifact_count: Option<i32>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        outcome_summary: Option<String>,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when an agent status changes
    AgentStatus {
        agent_id: String,
        name: String,
        status: String,
        current_task_id: Option<String>,
        /// The runtime agent instance identifier (e.g. "code_agent::a1b2c3d4").
        agent_instance_id: String,
        /// The template this instance was spawned from (e.g. "code_agent").
        template_id: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when a key status changes (add/remove/reorder)
    KeyStatusChanged {
        provider: String,
        key_id: String,
        status: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when a chat stream starts
    ChatStreamStarted {
        stream_id: String,
        lane_key: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when a chat stream ends
    ChatStreamEnded {
        stream_id: String,
        lane_key: String,
        status: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when an agent config is created, updated, or deleted
    AgentConfigChanged {
        agent_id: String,
        action: String, // "created" | "updated" | "deleted"
        config_version: u64,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when orchestrator config changes
    OrchestratorConfigChanged {
        model: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when daemon config changes (e.g. execution limits, server settings)
    DaemonConfigChanged {
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when a DAG node starts or completes
    DagNodeStatus {
        task_id: String,
        node_id: String,
        node_title: String,
        agent_id: String,
        /// "started" | "completed" | "failed"
        status: String,
        duration_ms: Option<u64>,
        output_preview: Option<String>,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// A security policy was violated by an agent
    SecurityViolation {
        agent_id: String,
        tool_name: String,
        reason: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// A tool's circuit breaker was tripped due to repeated failures
    CircuitBreakerTripped {
        agent_id: String,
        tool_name: String,
        consecutive_failures: usize,
        reset_after_secs: u64,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// A tool was executed by an agent
    ToolExecuted {
        agent_id: String,
        tool_name: String,
        success: bool,
        duration_ms: u64,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// An LLM call completed
    LlmCallCompleted {
        agent_id: String,
        model: String,
        input_tokens: u32,
        output_tokens: u32,
        cost_usd: f64,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// The skill catalog was updated (skill added, removed, or reloaded)
    SkillCatalogUpdated {
        skill_name: String,
        /// "added" | "removed" | "reloaded"
        action: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// A skill invocation started
    SkillInvocationStarted {
        request_id: String,
        skill_id: String,
        query_preview: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// A skill invocation completed successfully
    SkillCompleted {
        request_id: String,
        skill_id: String,
        duration_ms: u64,
        output_preview: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// A skill invocation failed
    SkillFailed {
        request_id: String,
        skill_id: String,
        error: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// A tool requires interactive human confirmation before execution
    ToolConfirmationRequested {
        request_id: String,
        agent_id: String,
        tool_name: String,
        tool_arguments: serde_json::Value,
        stream_id: Option<String>,
        lane_key: Option<String>,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when SOUL.md personality is updated
    SoulUpdated {
        /// Who initiated: "agent" or "user"
        actor: String,
        /// Update mode: "replace" or "sections"
        mode: String,
        /// SHA-256 hash of the new content
        content_sha256: String,
        /// Path to backup file (if created)
        backup_path: Option<String>,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// A background workflow was started for a lane (Routing V2)
    WorkflowStarted {
        task_id: String,
        lane_key: String,
        title: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// A steering message was accepted into a running workflow's inbox (Routing V2)
    WorkflowSteered {
        task_id: String,
        lane_key: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// A running workflow posted a user-facing progress update (Routing V2)
    WorkflowProgress {
        task_id: String,
        lane_key: String,
        message: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// A follow-up item was queued for a lane (Routing V2)
    FollowupQueued {
        lane_key: String,
        followup_id: i64,
        /// "followup" | "unprocessed_steering"
        kind: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// A plugin was loaded and registered its tools
    PluginLoaded {
        plugin_id: String,
        tools: Vec<String>,
    },
    /// A plugin was unloaded (graceful shutdown)
    PluginUnloaded {
        plugin_id: String,
    },
    /// A plugin process crashed unexpectedly
    PluginCrashed {
        plugin_id: String,
        error: String,
        restart_in_secs: u64,
    },
    /// A plugin was disabled by the system or user
    PluginDisabled {
        plugin_id: String,
        reason: String,
    },
    /// A plugin requires capability approval before activation
    PluginPendingApproval {
        plugin_id: String,
        capabilities: Vec<String>,
    },
    /// A plugin needs configuration keys before it can start
    PluginNeedsConfig {
        plugin_id: String,
        missing_keys: Vec<String>,
    },
}

// ── Unified Event System (M3.5) ────────────────────────────────────

/// Unique identifier for a unified event.
pub type EventId = Uuid;

/// The source of an event, identifying which connector or interface originated it.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(tag = "source_type", rename_all = "snake_case")]
pub enum EventSource {
    Telegram { chat_id: String, user_id: String },
    IMessage { chat_id: String, sender: String },
    Discord { channel_id: String, user_id: String, guild_id: Option<String> },
    Gui { connection_id: String },
    Api { request_id: String },
    Internal,
}

/// The payload carried by a unified event.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(tag = "payload_type", rename_all = "snake_case")]
pub enum EventPayload {
    UserMessage {
        content: String,
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        attachment_ids: Vec<String>,
    },
    Command {
        name: String,
        args: Vec<String>,
    },
    StatusChange {
        entity: String,
        old: String,
        new: String,
    },
}

/// A unified event that all connectors translate into.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UnifiedEvent {
    pub id: EventId,
    pub timestamp: DateTime<Utc>,
    pub source: EventSource,
    pub payload: EventPayload,
}

impl UnifiedEvent {
    /// Create a new UnifiedEvent with an auto-generated id and current timestamp.
    pub fn new(source: EventSource, payload: EventPayload) -> Self {
        Self {
            id: Uuid::new_v4(),
            timestamp: Utc::now(),
            source,
            payload,
        }
    }
}

#[cfg(test)]
mod tests;
