#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Install OpenAlpaca on macOS (no Cargo required on target machine).

Usage:
  install.sh --file <archive.tar.gz> [--prefix <dir>] [--app-dir <dir>] [--yes]
  install.sh --url  <https://.../archive.tar.gz> [--prefix <dir>] [--app-dir <dir>] [--yes]

Options:
  --file <path>    Install from a local tar.gz archive.
  --url <url>      Install from a remote tar.gz URL.
  --prefix <dir>   Install binaries under this prefix. Default: ~/.local/openalpaca
  --app-dir <dir>  Install app bundle under this directory. Default: ~/Applications
  --yes            Non-interactive overwrite of existing install.
EOF
}

die() {
  echo "ERROR: $*" >&2
  exit 1
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Required command not found: $1"
}

read_manifest_value() {
  local key="$1"
  local manifest="$2"
  local value

  if command -v jq >/dev/null 2>&1; then
    value="$(jq -r ".[\"$key\"] // empty" "$manifest")"
  else
    # Fallback: grep+sed for single-key-per-line pretty-printed JSON
    # (generated by package-macos.sh in a known format).
    value="$(grep -E "\"${key}\"[[:space:]]*:" "$manifest" | head -n1 | sed -E 's/.*:[[:space:]]*"([^"]+)".*/\1/')"
  fi

  [[ -n "$value" ]] || die "Could not read '${key}' from manifest: $manifest"
  printf '%s\n' "$value"
}

copy_missing_tree() {
  local src="$1"
  local dst="$2"

  [[ -d "$src" ]] || return 0
  mkdir -p "$dst"

  while IFS= read -r -d '' dir; do
    local rel="${dir#"$src"/}"
    if [[ "$dir" == "$src" ]]; then
      continue
    fi
    mkdir -p "$dst/$rel"
  done < <(find "$src" -type d -print0)

  while IFS= read -r -d '' file; do
    local rel="${file#"$src"/}"
    local target="$dst/$rel"
    if [[ -e "$target" ]]; then
      continue
    fi
    mkdir -p "$(dirname "$target")"
    cp "$file" "$target"
  done < <(find "$src" -type f -print0)
}

append_path_block() {
  local rc="$1"
  local marker_begin="# >>> openalpaca path >>>"
  local marker_end="# <<< openalpaca path <<<"

  touch "$rc"
  if grep -Fq "$marker_begin" "$rc"; then
    return 0
  fi

  {
    echo ""
    echo "$marker_begin"
    echo 'if [ -d "$HOME/.local/bin" ] && ! echo ":$PATH:" | grep -q ":$HOME/.local/bin:"; then'
    echo '  export PATH="$HOME/.local/bin:$PATH"'
    echo "fi"
    echo "$marker_end"
  } >>"$rc"
}

host_target() {
  case "$(uname -m)" in
    arm64) echo "aarch64-apple-darwin" ;;
    x86_64) echo "x86_64-apple-darwin" ;;
    *) die "Unsupported macOS architecture: $(uname -m)" ;;
  esac
}

verify_sha_if_available() {
  local archive_path="$1"
  local local_sha_file="$2"
  local expected=""

  if [[ -f "$local_sha_file" ]]; then
    expected="$(awk '{print $1}' "$local_sha_file" | head -n1)"
  fi

  if [[ -z "$expected" ]]; then
    return 0
  fi

  local actual
  actual="$(shasum -a 256 "$archive_path" | awk '{print $1}')"
  [[ "$actual" == "$expected" ]] || die "SHA256 mismatch. expected=$expected actual=$actual"
  echo "Verified SHA256 checksum."
}

stop_running_daemon_if_any() {
  local discovery_json="$HOME/Library/Application Support/OpenAlpaca/discovery.json"
  if [[ ! -f "$discovery_json" ]]; then
    return 0
  fi

  local pid=""
  pid="$(grep -Eo '"pid"[[:space:]]*:[[:space:]]*[0-9]+' "$discovery_json" | head -n1 | grep -Eo '[0-9]+' || true)"
  if [[ -z "$pid" ]]; then
    return 0
  fi

  if kill -0 "$pid" >/dev/null 2>&1; then
    echo "Stopping running daemon (pid=$pid)..."
    kill "$pid" >/dev/null 2>&1 || true
    local waited=0
    while kill -0 "$pid" >/dev/null 2>&1 && [ "$waited" -lt 10 ]; do
      sleep 1
      waited=$((waited + 1))
    done
    if kill -0 "$pid" >/dev/null 2>&1; then
      echo "Warning: daemon did not exit within 10s, proceeding anyway."
    fi
  fi
}

SOURCE_FILE=""
SOURCE_URL=""
PREFIX="$HOME/.local/openalpaca"
APP_DIR="$HOME/Applications"
NON_INTERACTIVE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --file)
      [[ $# -ge 2 ]] || die "--file requires a value"
      SOURCE_FILE="$2"
      shift 2
      ;;
    --url)
      [[ $# -ge 2 ]] || die "--url requires a value"
      SOURCE_URL="$2"
      shift 2
      ;;
    --prefix)
      [[ $# -ge 2 ]] || die "--prefix requires a value"
      PREFIX="$2"
      shift 2
      ;;
    --app-dir)
      [[ $# -ge 2 ]] || die "--app-dir requires a value"
      APP_DIR="$2"
      shift 2
      ;;
    --yes)
      NON_INTERACTIVE=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "Unknown argument: $1"
      ;;
  esac
done

[[ "$(uname -s)" == "Darwin" ]] || die "This installer currently supports macOS only."
[[ -n "$SOURCE_FILE" || -n "$SOURCE_URL" ]] || die "Provide either --file or --url."
[[ -z "$SOURCE_FILE" || -z "$SOURCE_URL" ]] || die "Use only one source: --file or --url."

require_cmd tar
require_cmd shasum
require_cmd awk
require_cmd sed
require_cmd grep
if [[ -n "$SOURCE_URL" ]]; then
  require_cmd curl
fi

if [[ -n "$SOURCE_FILE" ]]; then
  [[ -f "$SOURCE_FILE" ]] || die "Archive not found: $SOURCE_FILE"
fi

TMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/openalpaca-install-XXXXXX")"
trap 'rm -rf "$TMP_DIR"' EXIT

ARCHIVE_PATH="$TMP_DIR/openalpaca.tar.gz"
SHA_FILE_PATH="$TMP_DIR/openalpaca.tar.gz.sha256"

if [[ -n "$SOURCE_URL" ]]; then
  echo "Downloading archive from $SOURCE_URL ..."
  curl -fsSL "$SOURCE_URL" -o "$ARCHIVE_PATH"
  if curl -fsSL "${SOURCE_URL}.sha256" -o "$SHA_FILE_PATH"; then
    :
  else
    rm -f "$SHA_FILE_PATH"
  fi
else
  cp "$SOURCE_FILE" "$ARCHIVE_PATH"
  if [[ -f "${SOURCE_FILE}.sha256" ]]; then
    cp "${SOURCE_FILE}.sha256" "$SHA_FILE_PATH"
  fi
fi

verify_sha_if_available "$ARCHIVE_PATH" "$SHA_FILE_PATH"

echo "Extracting archive ..."
tar -xzf "$ARCHIVE_PATH" -C "$TMP_DIR" --strip-components=1
PACKAGE_ROOT="$TMP_DIR"
MANIFEST_PATH="$PACKAGE_ROOT/manifest.json"
[[ -f "$MANIFEST_PATH" ]] || die "manifest.json not found in archive."

MANIFEST_TARGET="$(read_manifest_value target "$MANIFEST_PATH")"
MANIFEST_VERSION="$(read_manifest_value version "$MANIFEST_PATH")"
HOST_TARGET="$(host_target)"
[[ "$MANIFEST_TARGET" == "$HOST_TARGET" ]] || die "Target mismatch: host=$HOST_TARGET package=$MANIFEST_TARGET"

if [[ -e "$PREFIX/bin/openalpaca" || -e "$APP_DIR/openalpaca-gui.app" ]]; then
  if [[ "$NON_INTERACTIVE" -ne 1 ]]; then
    read -r -p "Existing installation detected. Overwrite binaries and app bundle? [y/N] " confirm
    case "$confirm" in
      y|Y|yes|YES) ;;
      *) echo "Installation cancelled."; exit 0 ;;
    esac
  fi
fi

stop_running_daemon_if_any

echo "Installing binaries to $PREFIX ..."
mkdir -p "$PREFIX/bin" "$PREFIX/libexec"
install -m 755 "$PACKAGE_ROOT/bin/openalpaca" "$PREFIX/bin/openalpaca"
install -m 755 "$PACKAGE_ROOT/libexec/openalpacad" "$PREFIX/libexec/openalpacad"

echo "Installing GUI app to $APP_DIR ..."
mkdir -p "$APP_DIR"
rm -rf "$APP_DIR/openalpaca-gui.app"
cp -R "$PACKAGE_ROOT/gui/openalpaca-gui.app" "$APP_DIR/openalpaca-gui.app"

APP_SUPPORT_DIR="$HOME/Library/Application Support/OpenAlpaca"
CONFIG_DIR="$APP_SUPPORT_DIR/config"
mkdir -p "$CONFIG_DIR"
copy_missing_tree "$PACKAGE_ROOT/config" "$CONFIG_DIR"

mkdir -p "$HOME/.local/bin"
ln -sfn "$PREFIX/bin/openalpaca" "$HOME/.local/bin/openalpaca"

append_path_block "$HOME/.zshrc"
append_path_block "$HOME/.bashrc"

if [ -n "${SHELL:-}" ] && ! echo "$SHELL" | grep -qE '(bash|zsh)$'; then
  echo "Note: Your shell ($SHELL) is not bash/zsh."
  echo "      Add $HOME/.local/bin to your PATH manually to use 'openalpaca' from anywhere."
fi

if command -v xattr >/dev/null 2>&1; then
  xattr -dr com.apple.quarantine "$PREFIX" "$APP_DIR/openalpaca-gui.app" >/dev/null 2>&1 || true
fi

echo "OpenAlpaca $MANIFEST_VERSION installed successfully."
echo "CLI: $HOME/.local/bin/openalpaca"
echo "GUI: $APP_DIR/openalpaca-gui.app"
echo "Config: $CONFIG_DIR"
echo "If this is your first install, restart your shell or run: export PATH=\"\$HOME/.local/bin:\$PATH\""
