//\! Static registry of all known configuration keys.

use super::{ConfigBackend, ConfigKeyDef, ConfigKind};

/// Static registry of all known config keys.
pub static CONFIG_KEYS: &[ConfigKeyDef] = &[
    // -- Connectors --
    ConfigKeyDef {
        key: "telegram.token",
        kind: ConfigKind::String,
        default: None,
        description: "Telegram Bot API token from @BotFather",
        category: "Connectors",
        subcategory: None,
        sensitive: true,
        backend: ConfigBackend::SystemConfig,
    },
    ConfigKeyDef {
        key: "telegram.enabled",
        kind: ConfigKind::Bool,
        default: Some("false"),
        description: "Enable Telegram connector",
        category: "Connectors",
        subcategory: None,
        sensitive: false,
        backend: ConfigBackend::SystemConfig,
    },
    ConfigKeyDef {
        key: "telegram.notify_task_completion",
        kind: ConfigKind::Bool,
        default: Some("false"),
        description: "Global default for task completion notifications via Telegram. Per-user preferences (set via the preference system) override this value.",
        category: "Connectors",
        subcategory: None,
        sensitive: false,
        backend: ConfigBackend::SystemConfig,
    },
    ConfigKeyDef {
        key: "imessage.enabled",
        kind: ConfigKind::Bool,
        default: Some("false"),
        description: "Enable iMessage connector",
        category: "Connectors",
        subcategory: None,
        sensitive: false,
        backend: ConfigBackend::SystemConfig,
    },
    ConfigKeyDef {
        key: "imessage.allow_from_me",
        kind: ConfigKind::Bool,
        default: Some("true"),
        description: "Allow iMessage connector to process messages sent by this Mac user (useful for self-chat)",
        category: "Connectors",
        subcategory: None,
        sensitive: false,
        backend: ConfigBackend::SystemConfig,
    },
    ConfigKeyDef {
        key: "imessage.direct_require_prefix",
        kind: ConfigKind::Bool,
        default: Some("false"),
        description: "Require trigger prefix (/ask or @openalpaca) for direct (1-to-1) iMessages",
        category: "Connectors",
        subcategory: None,
        sensitive: false,
        backend: ConfigBackend::SystemConfig,
    },
    ConfigKeyDef {
        key: "imessage.group_require_prefix",
        kind: ConfigKind::Bool,
        default: Some("true"),
        description: "Require trigger prefix (/ask or @openalpaca) for group chat iMessages",
        category: "Connectors",
        subcategory: None,
        sensitive: false,
        backend: ConfigBackend::SystemConfig,
    },
    ConfigKeyDef {
        key: "imessage.bot_handle",
        kind: ConfigKind::String,
        default: None,
        description: "The iMessage sending address used by this Mac (e.g. bot@icloud.com or +1234567890). Messages from this account are filtered out to prevent feedback loops.",
        category: "Connectors",
        subcategory: None,
        sensitive: false,
        backend: ConfigBackend::SystemConfig,
    },
    ConfigKeyDef {
        key: "imessage.owner_handles",
        kind: ConfigKind::String,
        default: None,
        description: "Comma-separated list of iMessage handles (phone/email) belonging to the Mac owner, used to identify self-sent DMs",
        category: "Connectors",
        subcategory: None,
        sensitive: false,
        backend: ConfigBackend::SystemConfig,
    },
    ConfigKeyDef {
        key: "imessage.notify_task_completion",
        kind: ConfigKind::Bool,
        default: Some("false"),
        description: "Global default for task completion notifications via iMessage. Per-user preferences (set via the preference system) override this value.",
        category: "Connectors",
        subcategory: None,
        sensitive: false,
        backend: ConfigBackend::SystemConfig,
    },
    ConfigKeyDef {
        key: "discord.token",
        kind: ConfigKind::String,
        default: None,
        description: "Discord bot token",
        category: "Connectors",
        subcategory: None,
        sensitive: true,
        backend: ConfigBackend::SystemConfig,
    },
    ConfigKeyDef {
        key: "discord.enabled",
        kind: ConfigKind::Bool,
        default: Some("false"),
        description: "Enable Discord connector",
        category: "Connectors",
        subcategory: None,
        sensitive: false,
        backend: ConfigBackend::SystemConfig,
    },
    ConfigKeyDef {
        key: "discord.guild_id",
        kind: ConfigKind::String,
        default: None,
        description: "Optional: restrict the bot to a specific Discord server (guild ID snowflake)",
        category: "Connectors",
        subcategory: None,
        sensitive: false,
        backend: ConfigBackend::SystemConfig,
    },
    ConfigKeyDef {
        key: "discord.notify_task_completion",
        kind: ConfigKind::Bool,
        default: Some("false"),
        description: "Global default for task completion notifications via Discord. Per-user preferences override this value.",
        category: "Connectors",
        subcategory: None,
        sensitive: false,
        backend: ConfigBackend::SystemConfig,
    },
    // -- Daemon: Orchestrator --
    ConfigKeyDef {
        key: "daemon.orchestrator.prompt_recent_messages",
        kind: ConfigKind::Int {
            min: Some(1),
            max: Some(200),
        },
        default: Some("40"),
        description: "Number of recent messages kept in prompt context",
        category: "Daemon",
        subcategory: Some("Orchestrator"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.orchestrator.summary_max_chars",
        kind: ConfigKind::Int {
            min: Some(100),
            max: Some(32000),
        },
        default: Some("4000"),
        description: "Maximum summary length in characters",
        category: "Daemon",
        subcategory: Some("Orchestrator"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.orchestrator.summary_max_daily_cost_usd",
        kind: ConfigKind::Float {
            min: Some(0.0),
            max: Some(100.0),
        },
        default: Some("0.50"),
        description: "Daily cost cap for summarization (USD)",
        category: "Daemon",
        subcategory: Some("Orchestrator"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.orchestrator.identity_budget",
        kind: ConfigKind::Int {
            min: Some(50),
            max: Some(5000),
        },
        default: Some("300"),
        description: "Identity prompt budget in characters",
        category: "Daemon",
        subcategory: Some("Orchestrator"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.orchestrator.user_profile_budget",
        kind: ConfigKind::Int {
            min: Some(100),
            max: Some(10000),
        },
        default: Some("1000"),
        description: "User profile prompt budget in characters",
        category: "Daemon",
        subcategory: Some("Orchestrator"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    // -- Daemon: Execution --
    ConfigKeyDef {
        key: "daemon.execution.max_rounds",
        kind: ConfigKind::Int {
            min: Some(1),
            max: Some(100),
        },
        default: Some("15"),
        description: "Default max rounds per agent",
        category: "Daemon",
        subcategory: Some("Execution"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.execution.max_cost",
        kind: ConfigKind::Float {
            min: Some(0.0),
            max: Some(1000.0),
        },
        default: Some("1.00"),
        description: "Default max cost per agent (USD)",
        category: "Daemon",
        subcategory: Some("Execution"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.execution.lead_max_rounds",
        kind: ConfigKind::Int {
            min: Some(1),
            max: Some(200),
        },
        default: Some("18"),
        description: "Lead agent max rounds",
        category: "Daemon",
        subcategory: Some("Execution"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.execution.lead_max_cost",
        kind: ConfigKind::Float {
            min: Some(0.0),
            max: Some(1000.0),
        },
        default: Some("5.0"),
        description: "Lead agent max cost (USD)",
        category: "Daemon",
        subcategory: Some("Execution"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    // -- Daemon: Orchestrator (cont.) --
    ConfigKeyDef {
        key: "daemon.orchestrator.summary_min_new_older_messages",
        kind: ConfigKind::Int {
            min: Some(1),
            max: Some(200),
        },
        default: Some("12"),
        description: "Min new older messages before triggering summary",
        category: "Daemon",
        subcategory: Some("Orchestrator"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.orchestrator.msg_trunc_chars",
        kind: ConfigKind::Int {
            min: Some(100),
            max: Some(32000),
        },
        default: Some("1500"),
        description: "Character limit for message truncation in summary input",
        category: "Daemon",
        subcategory: Some("Orchestrator"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.orchestrator.extract_max_daily_cost_usd",
        kind: ConfigKind::Float {
            min: Some(0.0),
            max: Some(100.0),
        },
        default: Some("0.25"),
        description: "Daily cost cap for memory extractions (USD)",
        category: "Daemon",
        subcategory: Some("Orchestrator"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.orchestrator.extract_every_n_turns",
        kind: ConfigKind::Int {
            min: Some(1),
            max: Some(100),
        },
        default: Some("5"),
        description: "Run memory extraction every N user turns",
        category: "Daemon",
        subcategory: Some("Orchestrator"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.orchestrator.extract_min_content_len",
        kind: ConfigKind::Int {
            min: Some(1),
            max: Some(10000),
        },
        default: Some("20"),
        description: "Min content length (chars) to trigger extraction",
        category: "Daemon",
        subcategory: Some("Orchestrator"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    // -- Daemon: Orchestrator – Task Extraction --
    ConfigKeyDef {
        key: "daemon.orchestrator.task_extract_enabled",
        kind: ConfigKind::Bool,
        default: Some("true"),
        description: "Enable task output memory extraction",
        category: "Daemon",
        subcategory: Some("Orchestrator"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.orchestrator.task_extract_max_daily_cost_usd",
        kind: ConfigKind::Float {
            min: Some(0.0),
            max: Some(100.0),
        },
        default: Some("0.50"),
        description: "Daily cost cap for task output extraction (USD)",
        category: "Daemon",
        subcategory: Some("Orchestrator"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.orchestrator.task_extract_min_content_len",
        kind: ConfigKind::Int {
            min: Some(1),
            max: Some(10000),
        },
        default: Some("100"),
        description: "Min task output length (chars) for extraction",
        category: "Daemon",
        subcategory: Some("Orchestrator"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    // -- Daemon: Orchestrator – Background Models --
    ConfigKeyDef {
        key: "daemon.orchestrator.summary_model",
        kind: ConfigKind::String,
        default: None,
        description: "Model ID for background summary generation (e.g. claude-haiku-4-5-20251001). Uses router default if empty.",
        category: "Daemon",
        subcategory: Some("Orchestrator"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.orchestrator.extraction_model",
        kind: ConfigKind::String,
        default: None,
        description: "Model ID for background user trait extraction (e.g. claude-haiku-4-5-20251001). Uses router default if empty.",
        category: "Daemon",
        subcategory: Some("Orchestrator"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    // -- Daemon: Orchestrator – Supersession --
    ConfigKeyDef {
        key: "daemon.orchestrator.supersession_distance_threshold",
        kind: ConfigKind::Float {
            min: Some(0.0),
            max: Some(10.0),
        },
        default: Some("1.0"),
        description: "L2 distance threshold for semantic supersession",
        category: "Daemon",
        subcategory: Some("Orchestrator"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.orchestrator.fts_jaccard_threshold",
        kind: ConfigKind::Float {
            min: Some(0.0),
            max: Some(1.0),
        },
        default: Some("0.4"),
        description: "Jaccard overlap threshold for FTS supersession fallback",
        category: "Daemon",
        subcategory: Some("Orchestrator"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    // -- Daemon: Orchestrator – Decay --
    ConfigKeyDef {
        key: "daemon.orchestrator.decay_poll_interval_secs",
        kind: ConfigKind::Int {
            min: Some(60),
            max: Some(86400),
        },
        default: Some("3600"),
        description: "How often to run the decay task (seconds)",
        category: "Daemon",
        subcategory: Some("Orchestrator"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.orchestrator.decay_half_life_days",
        kind: ConfigKind::Float {
            min: Some(1.0),
            max: Some(365.0),
        },
        default: Some("30.0"),
        description: "Half-life in days for importance decay",
        category: "Daemon",
        subcategory: Some("Orchestrator"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.orchestrator.decay_min_importance",
        kind: ConfigKind::Float {
            min: Some(0.0),
            max: Some(1.0),
        },
        default: Some("0.05"),
        description: "Min importance floor; below this memories are prune-eligible",
        category: "Daemon",
        subcategory: Some("Orchestrator"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.orchestrator.decay_soft_cap",
        kind: ConfigKind::Int {
            min: Some(10),
            max: Some(100000),
        },
        default: Some("500"),
        description: "Soft cap on total memories per owner",
        category: "Daemon",
        subcategory: Some("Orchestrator"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    // -- Daemon: Execution (cont.) --
    ConfigKeyDef {
        key: "daemon.execution.max_tools_per_round",
        kind: ConfigKind::Int {
            min: Some(1),
            max: Some(50),
        },
        default: Some("5"),
        description: "Default max tool calls per agent round",
        category: "Daemon",
        subcategory: Some("Execution"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.execution.max_tool_runtime_secs",
        kind: ConfigKind::Int {
            min: Some(1),
            max: Some(600),
        },
        default: Some("60"),
        description: "Default max tool runtime in seconds",
        category: "Daemon",
        subcategory: Some("Execution"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.execution.lead_max_tools_per_round",
        kind: ConfigKind::Int {
            min: Some(1),
            max: Some(50),
        },
        default: Some("3"),
        description: "Lead agent max tool calls per round",
        category: "Daemon",
        subcategory: Some("Execution"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.execution.lead_max_tool_runtime_secs",
        kind: ConfigKind::Int {
            min: Some(1),
            max: Some(3600),
        },
        default: Some("300"),
        description: "Lead agent max tool runtime in seconds",
        category: "Daemon",
        subcategory: Some("Execution"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.execution.lead_max_concurrent_subagents",
        kind: ConfigKind::Int {
            min: Some(1),
            max: Some(32),
        },
        default: Some("6"),
        description: "Maximum concurrent subagents per lead agent",
        category: "Daemon",
        subcategory: Some("Execution"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    // -- Daemon: Security --
    ConfigKeyDef {
        key: "daemon.security.max_input_length",
        kind: ConfigKind::Int {
            min: Some(1024),
            max: Some(1_048_576),
        },
        default: Some("32768"),
        description: "Maximum user input length in bytes",
        category: "Daemon",
        subcategory: Some("Security"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    // -- Daemon: Orchestrator – Routing (Routing V2) --
    ConfigKeyDef {
        key: "daemon.orchestrator.routing.steering_enabled",
        kind: ConfigKind::Bool,
        default: Some("true"),
        description: "Enable mid-workflow steering (per-workflow inboxes, /steer, steer_workflow tools)",
        category: "Daemon",
        subcategory: Some("Routing"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.orchestrator.routing.steering_inbox_cap",
        kind: ConfigKind::Int {
            min: Some(1),
            max: Some(1024),
        },
        default: Some("16"),
        description: "Max queued steering messages per workflow inbox",
        category: "Daemon",
        subcategory: Some("Routing"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.orchestrator.routing.max_workflows_per_lane",
        kind: ConfigKind::Int {
            min: Some(1),
            max: Some(32),
        },
        default: Some("3"),
        description: "Max concurrent background workflows per conversation lane",
        category: "Daemon",
        subcategory: Some("Routing"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.orchestrator.routing.followup_autostart",
        kind: ConfigKind::Bool,
        default: Some("true"),
        description: "Auto-start the next queued follow-up when a workflow finalizes",
        category: "Daemon",
        subcategory: Some("Routing"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.orchestrator.routing.main_loop_max_rounds",
        kind: ConfigKind::Int {
            min: Some(1),
            max: Some(100),
        },
        default: Some("8"),
        description: "Main-loop max agentic rounds per user turn",
        category: "Daemon",
        subcategory: Some("Routing"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.orchestrator.routing.main_loop_max_tools_per_round",
        kind: ConfigKind::Int {
            min: Some(1),
            max: Some(50),
        },
        default: Some("4"),
        description: "Main-loop max tool calls per round",
        category: "Daemon",
        subcategory: Some("Routing"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.orchestrator.routing.tool_selection",
        kind: ConfigKind::Enum(&["core_union", "full"]),
        default: Some("core_union"),
        description: "Main-loop tool surface: core_union (suggested + core set) or full (entire registry minus deny list)",
        category: "Daemon",
        subcategory: Some("Routing"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.orchestrator.routing.scheduled_skills_enabled",
        kind: ConfigKind::Bool,
        default: Some("true"),
        description: "Enable cron-scheduled skills (invoke.cron frontmatter)",
        category: "Daemon",
        subcategory: Some("Routing"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    // -- Daemon: Server --
    ConfigKeyDef {
        key: "daemon.server.heartbeat_interval_secs",
        kind: ConfigKind::Int {
            min: Some(1),
            max: Some(300),
        },
        default: Some("5"),
        description: "WebSocket heartbeat interval in seconds",
        category: "Daemon",
        subcategory: Some("Server"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.server.sse_keep_alive_secs",
        kind: ConfigKind::Int {
            min: Some(1),
            max: Some(300),
        },
        default: Some("15"),
        description: "SSE keep-alive interval in seconds",
        category: "Daemon",
        subcategory: Some("Server"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.server.event_broadcaster_capacity",
        kind: ConfigKind::Int {
            min: Some(8),
            max: Some(1024),
        },
        default: Some("64"),
        description: "Event broadcaster channel capacity (restart-only)",
        category: "Daemon",
        subcategory: Some("Server"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.server.wake_channel_capacity",
        kind: ConfigKind::Int {
            min: Some(8),
            max: Some(4096),
        },
        default: Some("256"),
        description: "Wake event channel capacity (restart-only)",
        category: "Daemon",
        subcategory: Some("Server"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.server.cleanup_interval_secs",
        kind: ConfigKind::Int {
            min: Some(5),
            max: Some(3600),
        },
        default: Some("60"),
        description: "Chat stream stale cleanup interval in seconds",
        category: "Daemon",
        subcategory: Some("Server"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.server.stale_timeout_secs",
        kind: ConfigKind::Int {
            min: Some(5),
            max: Some(3600),
        },
        default: Some("30"),
        description: "Chat stream stale timeout in seconds",
        category: "Daemon",
        subcategory: Some("Server"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.server.stream_chunk_delay_ms",
        kind: ConfigKind::Int {
            min: Some(0),
            max: Some(500),
        },
        default: Some("30"),
        description: "Delay in milliseconds between streaming word chunks (0 = no delay)",
        category: "Daemon",
        subcategory: Some("Server"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.server.stream_chunk_words",
        kind: ConfigKind::Int {
            min: Some(1),
            max: Some(50),
        },
        default: Some("3"),
        description: "Number of words per streaming delta chunk",
        category: "Daemon",
        subcategory: Some("Server"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.server.embedding_poll_interval_secs",
        kind: ConfigKind::Int {
            min: Some(5),
            max: Some(3600),
        },
        default: Some("30"),
        description: "Embedding indexer poll interval in seconds",
        category: "Daemon",
        subcategory: Some("Server"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    ConfigKeyDef {
        key: "daemon.server.embedding_batch_size",
        kind: ConfigKind::Int {
            min: Some(1),
            max: Some(500),
        },
        default: Some("50"),
        description: "Embedding indexer batch size per run",
        category: "Daemon",
        subcategory: Some("Server"),
        sensitive: false,
        backend: ConfigBackend::DaemonToml,
    },
    // -- Web Search (stored in llm.toml) --
    ConfigKeyDef {
        key: "ai.web_search.api_key",
        kind: ConfigKind::String,
        default: None,
        description: "Brave Search API key (get one at https://brave.com/search/api/)",
        category: "AI",
        subcategory: Some("Web Search"),
        sensitive: true,
        backend: ConfigBackend::LlmToml,
    },
    ConfigKeyDef {
        key: "ai.web_search.timeout_secs",
        kind: ConfigKind::Int {
            min: Some(1),
            max: Some(60),
        },
        default: Some("15"),
        description: "Brave Search request timeout in seconds",
        category: "AI",
        subcategory: Some("Web Search"),
        sensitive: false,
        backend: ConfigBackend::LlmToml,
    },
    // -- Agents --
    ConfigKeyDef {
        key: "ai.default_model",
        kind: ConfigKind::String,
        default: Some("claude-sonnet-4-5-20250929"),
        description: "Default LLM model for orchestration",
        category: "Agents",
        subcategory: Some("Orchestrator"),
        sensitive: false,
        backend: ConfigBackend::LlmToml,
    },
    ConfigKeyDef {
        key: "ai.fallback_models",
        kind: ConfigKind::String,
        default: None,
        description: "Comma-separated fallback model list",
        category: "Agents",
        subcategory: Some("Orchestrator"),
        sensitive: false,
        backend: ConfigBackend::LlmToml,
    },
    // -- Agents: Embeddings --
    ConfigKeyDef {
        key: "ai.embeddings.enabled",
        kind: ConfigKind::Bool,
        default: Some("true"),
        description: "Enable embedding generation for semantic memory search",
        category: "Agents",
        subcategory: Some("Embeddings"),
        sensitive: false,
        backend: ConfigBackend::LlmToml,
    },
    ConfigKeyDef {
        key: "ai.embeddings.provider",
        kind: ConfigKind::String,
        default: Some("local"),
        description: "Embedding provider (local, openai, or ollama)",
        category: "Agents",
        subcategory: Some("Embeddings"),
        sensitive: false,
        backend: ConfigBackend::LlmToml,
    },
    ConfigKeyDef {
        key: "ai.embeddings.model",
        kind: ConfigKind::String,
        default: Some("intfloat/multilingual-e5-base"),
        description: "Embedding model name",
        category: "Agents",
        subcategory: Some("Embeddings"),
        sensitive: false,
        backend: ConfigBackend::LlmToml,
    },
    ConfigKeyDef {
        key: "ai.embeddings.dimensions",
        kind: ConfigKind::Int {
            min: Some(64),
            max: Some(4096),
        },
        default: Some("768"),
        description: "Embedding vector dimensions",
        category: "Agents",
        subcategory: Some("Embeddings"),
        sensitive: false,
        backend: ConfigBackend::LlmToml,
    },
    // -- API-Keys: Anthropic --
    ConfigKeyDef {
        key: "ai.anthropic.enabled",
        kind: ConfigKind::Bool,
        default: None,
        description: "Enable Anthropic provider",
        category: "API-Keys",
        subcategory: Some("Anthropic"),
        sensitive: false,
        backend: ConfigBackend::LlmToml,
    },
    ConfigKeyDef {
        key: "ai.anthropic.api_key",
        kind: ConfigKind::String,
        default: None,
        description: "Anthropic API key (encrypted at rest)",
        category: "API-Keys",
        subcategory: Some("Anthropic"),
        sensitive: true,
        backend: ConfigBackend::LlmToml,
    },
    // -- API-Keys: OpenAI --
    ConfigKeyDef {
        key: "ai.openai.enabled",
        kind: ConfigKind::Bool,
        default: None,
        description: "Enable OpenAI provider",
        category: "API-Keys",
        subcategory: Some("OpenAI"),
        sensitive: false,
        backend: ConfigBackend::LlmToml,
    },
    ConfigKeyDef {
        key: "ai.openai.api_key",
        kind: ConfigKind::String,
        default: None,
        description: "OpenAI API key (encrypted at rest)",
        category: "API-Keys",
        subcategory: Some("OpenAI"),
        sensitive: true,
        backend: ConfigBackend::LlmToml,
    },
    // -- API-Keys: Ollama --
    ConfigKeyDef {
        key: "ai.ollama.enabled",
        kind: ConfigKind::Bool,
        default: None,
        description: "Enable Ollama provider",
        category: "API-Keys",
        subcategory: Some("Ollama"),
        sensitive: false,
        backend: ConfigBackend::LlmToml,
    },
    ConfigKeyDef {
        key: "ai.ollama.base_url",
        kind: ConfigKind::String,
        default: None,
        description: "Ollama server base URL",
        category: "API-Keys",
        subcategory: Some("Ollama"),
        sensitive: false,
        backend: ConfigBackend::LlmToml,
    },
    // -- API-Keys: Claude Code --
    ConfigKeyDef {
        key: "ai.claude_code.discovery",
        kind: ConfigKind::Bool,
        default: Some("true"),
        description: "Auto-discover Claude Code OAuth token",
        category: "API-Keys",
        subcategory: Some("Claude Code"),
        sensitive: false,
        backend: ConfigBackend::LlmToml,
    },
    ConfigKeyDef {
        key: "ai.claude_code.cli_enabled",
        kind: ConfigKind::Bool,
        default: Some("true"),
        description: "Enable Claude Code CLI fallback",
        category: "API-Keys",
        subcategory: Some("Claude Code"),
        sensitive: false,
        backend: ConfigBackend::LlmToml,
    },
    ConfigKeyDef {
        key: "ai.claude_code.cli_path",
        kind: ConfigKind::String,
        default: None,
        description: "Override Claude Code CLI binary path",
        category: "API-Keys",
        subcategory: Some("Claude Code"),
        sensitive: false,
        backend: ConfigBackend::LlmToml,
    },
    // -- API-Keys: Codex --
    ConfigKeyDef {
        key: "ai.codex.discovery",
        kind: ConfigKind::Bool,
        default: Some("true"),
        description: "Auto-discover Codex OAuth token",
        category: "API-Keys",
        subcategory: Some("Codex"),
        sensitive: false,
        backend: ConfigBackend::LlmToml,
    },
    ConfigKeyDef {
        key: "ai.codex.cli_enabled",
        kind: ConfigKind::Bool,
        default: Some("true"),
        description: "Enable Codex CLI fallback",
        category: "API-Keys",
        subcategory: Some("Codex"),
        sensitive: false,
        backend: ConfigBackend::LlmToml,
    },
    ConfigKeyDef {
        key: "ai.codex.cli_path",
        kind: ConfigKind::String,
        default: None,
        description: "Override Codex CLI binary path",
        category: "API-Keys",
        subcategory: Some("Codex"),
        sensitive: false,
        backend: ConfigBackend::LlmToml,
    },
];
