[orchestrator]
model = "claude-sonnet-4-5-20250929"
fallback_models = ["claude-sonnet-4-5-20250929"]

[providers.ollama]
enabled = false
base_url = "http://localhost:11434/v1"

[providers.openai]
enabled = false

[providers.anthropic]
enabled = true

[[providers.anthropic.keys]]
id = "Claude Code Token"
secret_encrypted = "aes256:8uSUYCYI2LPOOOp3kBdAYsj57Fn5pocHIzXkPjUaPebQV4YPA5DOOK/UiJ+irLFwg5kr5psovDhnjmQ4Mvw9my/WmsHYalVaWGlVKKsj7a+KlZSrRg/DrKQMmI3L/xzwwutWbOQwT4vJPwmew3uf8O+50XiVIkASXvxQ1vUYL3LfXAocxw7FFg=="
priority = "fallback"
source = "claude_code"

[[providers.anthropic.keys]]
id = "Anthropic API Key"
secret_encrypted = "aes256:MeVZlPIVaS6WBXfwtuOi3sIfUafQB2v2CTFeBdnFCHWlJ8S+o70botMKMhjxVrFG+kNvOmjo2r3JAHM7q/IZS04z3VzHwa3SnGbqypfbW4MmCbMetVA4h9A3NTsZ5POy6AFtYg74lDKcGGdfCYVUOszRzKMiosZpELxm7CHWu/t4qLhg1VbNVw=="
tier = "tier3"
priority = "primary"
source = "api_console"

[credential_discovery]
claude_code = true

[cli_backends.claude_code]
enabled = false

[embeddings]
enabled = true
provider = "local"
model = "intfloat/multilingual-e5-base"
dimensions = 768
