[package]
name = "openalpaca"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
futures-util.workspace = true
tokio-tungstenite.workspace = true

# CLI
clap.workspace = true
reqwest = { workspace = true, features = ["stream"] }
tokio-stream.workspace = true
colored.workspace = true
urlencoding.workspace = true
dialoguer.workspace = true
console.workspace = true
nix.workspace = true
sysinfo.workspace = true
log.workspace = true
env_logger.workspace = true
rustyline.workspace = true

# Workspace crates
openalpaca_storage = { workspace = true }
