use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Wake events generated by the Wake module
/// Uses `kind` tag to avoid conflict with ServerEvent's `type` tag
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum WakeEvent {
    Timer { job_id: String, tag: String },
    FileChanged { path: String, change_type: String },
}

/// Server events pushed to clients via WebSocket
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ServerEvent {
    Heartbeat {
        ts: DateTime<Utc>,
        instance_id: String,
    },
    Log {
        level: String,
        message: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    CommandReceived {
        request_id: String,
        command: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered by the Wake module
    Wake {
        wake: WakeEvent,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when a connector status changes
    ConnectorStatus {
        id: String,
        status: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when a task status changes
    TaskStatus {
        task_id: String,
        title: String,
        status: String,
        progress_current: Option<i32>,
        progress_total: Option<i32>,
        result_summary: Option<String>,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when an agent status changes
    AgentStatus {
        agent_id: String,
        name: String,
        status: String,
        current_task_id: Option<String>,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when a key status changes (add/remove/reorder)
    KeyStatusChanged {
        provider: String,
        key_id: String,
        status: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when a chat stream starts
    ChatStreamStarted {
        stream_id: String,
        lane_key: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when a chat stream ends
    ChatStreamEnded {
        stream_id: String,
        lane_key: String,
        status: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when an agent config is created, updated, or deleted
    AgentConfigChanged {
        agent_id: String,
        action: String, // "created" | "updated" | "deleted"
        config_version: u64,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when orchestrator config changes
    OrchestratorConfigChanged {
        model: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered when SOUL.md personality is updated
    SoulUpdated {
        /// Who initiated: "agent" or "user"
        actor: String,
        /// Update mode: "replace" or "sections"
        mode: String,
        /// SHA-256 hash of the new content
        content_sha256: String,
        /// Path to backup file (if created)
        backup_path: Option<String>,
        ts: DateTime<Utc>,
        instance_id: String,
    },
}

// ── Unified Event System (M3.5) ────────────────────────────────────

/// Unique identifier for a unified event.
pub type EventId = Uuid;

/// The source of an event, identifying which connector or interface originated it.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(tag = "source_type", rename_all = "snake_case")]
pub enum EventSource {
    Telegram { chat_id: String, user_id: String },
    Gui { connection_id: String },
    Cli { session_id: String },
    Api { request_id: String },
    Internal,
}

/// The payload carried by a unified event.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(tag = "payload_type", rename_all = "snake_case")]
pub enum EventPayload {
    UserMessage {
        content: String,
    },
    Command {
        name: String,
        args: Vec<String>,
    },
    StatusChange {
        entity: String,
        old: String,
        new: String,
    },
}

/// A unified event that all connectors translate into.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UnifiedEvent {
    pub id: EventId,
    pub timestamp: DateTime<Utc>,
    pub source: EventSource,
    pub payload: EventPayload,
}

impl UnifiedEvent {
    /// Create a new UnifiedEvent with an auto-generated id and current timestamp.
    pub fn new(source: EventSource, payload: EventPayload) -> Self {
        Self {
            id: Uuid::new_v4(),
            timestamp: Utc::now(),
            source,
            payload,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_unified_event_creation() {
        let event = UnifiedEvent::new(
            EventSource::Cli {
                session_id: "sess-1".into(),
            },
            EventPayload::UserMessage {
                content: "hello".into(),
            },
        );
        assert!(!event.id.is_nil());
        assert_eq!(
            event.source,
            EventSource::Cli {
                session_id: "sess-1".into()
            }
        );
    }

    #[test]
    fn test_event_source_serialization_roundtrip() {
        let source = EventSource::Telegram {
            chat_id: "123".into(),
            user_id: "456".into(),
        };
        let json = serde_json::to_string(&source).unwrap();
        let deserialized: EventSource = serde_json::from_str(&json).unwrap();
        assert_eq!(source, deserialized);
    }

    #[test]
    fn test_event_payload_serialization_roundtrip() {
        let payload = EventPayload::Command {
            name: "help".into(),
            args: vec!["--verbose".into()],
        };
        let json = serde_json::to_string(&payload).unwrap();
        let deserialized: EventPayload = serde_json::from_str(&json).unwrap();
        assert_eq!(payload, deserialized);
    }

    #[test]
    fn test_unified_event_serialization_roundtrip() {
        let event = UnifiedEvent::new(
            EventSource::Internal,
            EventPayload::StatusChange {
                entity: "agent".into(),
                old: "idle".into(),
                new: "running".into(),
            },
        );
        let json = serde_json::to_string(&event).unwrap();
        let deserialized: UnifiedEvent = serde_json::from_str(&json).unwrap();
        assert_eq!(event.id, deserialized.id);
        assert_eq!(event.source, deserialized.source);
        assert_eq!(event.payload, deserialized.payload);
    }
}
