use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Wake events generated by the Wake module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", content = "data", rename_all = "snake_case")]
pub enum WakeEvent {
    Timer { job_id: String, tag: String },
    FileChanged { path: String, kind: String },
}

/// Server events pushed to clients via WebSocket
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ServerEvent {
    Heartbeat {
        ts: DateTime<Utc>,
        instance_id: String,
    },
    Log {
        level: String,
        message: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    CommandReceived {
        request_id: String,
        command: String,
        ts: DateTime<Utc>,
        instance_id: String,
    },
    /// Event triggered by the Wake module
    Wake {
        #[serde(flatten)]
        event: WakeEvent,
        ts: DateTime<Utc>,
        instance_id: String,
    },
}
