[package]
name = "openalpacad"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
futures-util.workspace = true

# Workspace crates
openalpaca_core = { path = "../../crates/openalpaca_core" }
openalpaca_api = { path = "../../crates/openalpaca_api" }
openalpaca_storage = { path = "../../crates/openalpaca_storage" }
openalpaca_wake = { path = "../../crates/openalpaca_wake" }
